### ISSUE TITLE
Problem when running this script

### ISSUE THREAD

**Issue by joelschmol** [warp-plus-cloudflare/cli#2]
When i run it, it returns the following

`*********************************
            WARP-PLUS-CLOUDFLARE By ALIILAPRO
            *********************************     
[+] ABOUT SCRIPT:                                 [-] With this script, you can getting unlimited GB on Warp+.                                        [-] Version: 4.1.0 beta
--------                                          [+] THIS SCRIPT CODDED BY ALIILAPRO
[-] SITE: aliilapro.github.io
[-] TELEGRAM: aliilapro
--------                                          Traceback (most recent call last):                  File "/storage/emulated/0/Download/wp-plus.py", line 32, in <module>
    response = urllib.request.urlopen(proxy_url)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>`

**Comment by tdppro** [comment]
![image](https://github.com/warp-plus-cloudflare/cli/assets/6672432/af8a39cf-5df7-443e-9aee-9bc9efe82944)
can't connect to server

**Comment by escape0707** [comment]
Maybe try again with a desktop environment, plus the output copied from Termux is hard to read...
